fieldLayouts:
  dc003097-b2e7-44c5-91c7-38144b424684:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: c45af8f2-0194-472a-aa1d-297d47f219dd # Image Text Callout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 87f0eeb1-40ea-41d2-9ea6-ec6c509201ff # Title
            instructions: ''
            label: 'Icon Callout Set Title'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 61022c53-1304-49ce-ba7c-0ed9a4127cc6 # Icon Callout Set
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 231f2176-2288-43e5-81de-871862891401 # Venn Diagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0ba69eab-d56c-4035-ac72-04a24930d9c0 # Title 2
            instructions: ''
            label: 'Photo Grid Title'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e8df2b6-8494-4d78-9623-dbd98f01ae2e # Photo Grid
            instructions: ''
            label: 'Photo Grid'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e170d527-1ae4-4311-a168-e1e707fc1237 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: about
hasTitleField: false
name: About
section: 2b8543ca-9853-4595-a460-022385356fb8 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
